import type { PerformanceRecord } from '@/types/performance'

export const sampleRecords: PerformanceRecord[] = [
  {
    id: 'grade-1',
    sync_run_id: null,
    grade_record_id: 'grade-1',
    employee_id: 'emp-a',
    cycle_id: 'c1',
    employee_name: 'Alice',
    cycle_name: '2024 H2',
    department: 'Engineering',
    team: 'Platform',
    display_grade: 'Exceeding',
    line_manager_grade: 'Exceeding',
    calculated_grade: 'Performing',
    absolute_rating: null,
    ranking_score: null,
    payload: {
      'Line Manager (HR profile)': 'Bob Manager',
      'Department Grade Calibrator': 'Cal A',
      'Grade Calibrated': 'true',
      'Scorecard Deliverables - Speed': 'Advanced',
      'Scorecard Values - Integrity': 'Expert',
      'All Scorecards (JSON)': JSON.stringify([
        {
          id: 'sc-1',
          reviewer: 'Bob',
          relation: 'line_manager',
          status: 'completed',
          opened: '2024-01-01',
          completed: '2024-01-05',
        },
        {
          id: 'sc-2',
          reviewer: 'Carol',
          relation: 'peer',
          status: 'completed',
          opened: '2024-01-02',
          completed: '2024-01-06',
        },
      ]),
    },
    synced_at: '2024-06-01T00:00:00.000Z',
  },
  {
    id: 'grade-2',
    sync_run_id: null,
    grade_record_id: 'grade-2',
    employee_id: 'emp-a',
    cycle_id: 'c2',
    employee_name: 'Alice',
    cycle_name: '2025 H1',
    department: 'Engineering',
    team: 'Platform',
    display_grade: 'Exceptional',
    line_manager_grade: 'Exceptional',
    calculated_grade: 'Exceptional',
    absolute_rating: null,
    ranking_score: null,
    payload: {
      'Line Manager (HR profile)': 'Bob Manager',
      'Cycle Timeline Status': 'completed',
      'Employee Cycle Outcome': 'confirmed',
    },
    synced_at: '2025-06-01T00:00:00.000Z',
  },
  {
    id: 'grade-3',
    sync_run_id: null,
    grade_record_id: 'grade-3',
    employee_id: 'emp-b',
    cycle_id: 'c1',
    employee_name: 'Ben',
    cycle_name: '2024 H2',
    department: 'Product',
    team: 'Growth',
    display_grade: 'Performing',
    line_manager_grade: 'Performing',
    calculated_grade: 'Performing',
    absolute_rating: null,
    ranking_score: null,
    payload: {},
    synced_at: '2024-06-01T00:00:00.000Z',
  },
]
